apiVersion: v1
kind: Service
metadata:
  name: {{ include "eks-app.fullname" . }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: {{ .Values.service.scheme }}
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "{{ .Values.service.acmArn }}"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
spec:
  type: LoadBalancer
  selector:
    app: {{ include "eks-app.name" . }}
  ports:
    - name: https
      port: 443
      targetPort: {{ .Values.service.targetPort }}
